package com.robosoft.weatherappjetpack.presentation.search

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.Icon
import androidx.compose.material.IconButton
import androidx.compose.material.Text
import androidx.compose.material.TextField
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowBack
import androidx.compose.material.icons.filled.Close
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.tooling.preview.Preview
import androidx.navigation.NavController


@Composable
fun Search(navController: NavController) {

    val cities = listOf(
        "Adilabad",
        "Agar Malwa",
        "Agaragarh",
        "Agartala",
        "Agra",
        "Ahmedabad",
        "Ahmednagar",
        "Aizawl",
        "Ajmer",
        "Akola",
        "Alappuzha",
        "Aligarh",
        "Alirajpur",
        "Almora",
        "Alwar",
        "Ambala",
        "Ambedkar Nagar",
        "Amethi",
        "Amravati",
        "Amreli",
        "Amritsar",
        "Amroha",
        "Anand",
        "Anantapur",
        "Anantnag",
        "Angul",
        "Anjaw",
        "Anuppur",
        "Araria",
        "Aravalli",
        "Ariyalur",
        "Arwal",
        "Ashoknagar",
        "Auraiya",
        "Aurangabad",
        "Azamgarh",
        "Badgam",
        "Bagalkot",
        "Bageshwar",
        "Bagpat",
        "Bahraich",
        "Baksa",
        "Balaghat",
        "Balangir",
        "Balasore",
        "Ballia",
        "Balod",
        "Baloda Bazar",
        "Balrampur",
        "Banaskantha",
        "Banda",
        "Bandipora",
        "Bangalore Rural",
        "Bangalore Urban",
        "Banka",
        "Bankura",
        "Banswara",
        "Barabanki",
        "Baramulla",
        "Baran",
        "Bardhaman",
        "Bareilly",
        "Bargarh",
        "Barmer",
        "Barnala",
        "Barpeta",
        "Barwani",
        "Bastar",
        "Basti",
        "Bathinda",
        "Beed",
        "Begusarai",
        "Belgaum",
        "Bellary",
        "Bemetara",
        "Betul",
        "Bhadrak",
        "Bhagalpur",
        "Bhandara",
        "Bharatpur",
        "Bharuch",
        "Bhavnagar",
        "Bhilwara",
        "Bhind",
        "Bhiwani",
        "Bhojpur",
        "Bhopal",
        "Bidar",
        "Bijapur",
        "Bijnor",
        "Bikaner",
        "Bilaspur",
        "Birbhum",
        "Bishnupur",
        "Bokaro",
        "Bongaigaon",
        "Boudh",
        "Budaun",
        "Bulandshahr",
        "Buldhana",
        "Bundi",
        "Burhanpur",
        "Buxar",
        "Cachar",
        "Central Delhi",
        "Chamarajanagar",
        "Chamba",
        "Chamoli",
        "Champawat",
        "Champhai",
        "Chandauli",
        "Chandel",
        "Chandigarh",
        "Chandrapur",
        "Changlang",
        "Chatra",
        "Chengalpattu",
        "Chennai",
        "Chhatarpur",
        "Chhatrapati Shahuji Maharaj Nagar",
        "Chhindwara",
        "Chhota Udaipur",
        "Chikkaballapur",
        "Chikkamagaluru",
        "Chirang",
        "Chitradurga",
        "Chitrakoot",
        "Chittoor",
        "Chittorgarh",
        "Churachandpur",
        "Churu",
        "Coimbatore",
        "Cooch Behar",
        "Cuddalore",
        "Cuttack",
        "Dadra and Nagar Haveli",
        "Dahod",
        "Dakshina Kannada",
        "Daman",
        "Damoh",
        "Dang",
        "Darbhanga",
        "Darjeeling",
        "Darrang",
        "Datia",
        "Dausa",
        "Davanagere",
        "Debagarh",
        "Dehradun",
        "Deogarh",
        "Deoghar",
        "Deoria",
        "Devbhoomi Dwarka",
        "Dewas",
        "Dhalai",
        "Dhamtari",
        "Dhanbad",
        "Dhar",
        "Dharmapuri",
        "Dharwad",
        "Dhemaji",
        "Dhenkanal",
        "Dholpur",
        "Dhubri",
        "Dhule",
        "Dibang Valley",
        "Dibrugarh",
        "Dima Hasao",
        "Dimapur",
        "Dindigul",
        "Dindori",
        "Diu",
        "Doda",
        "East Garo Hills",
        "East Godavari",
        "East Jaintia Hills",
        "East Kameng",
        "East Khasi Hills",
        "East Siang",
        "Eluru",
        "Ernakulam",
        "Erode",
        "Etah",
        "Etawah",
        "Faridabad",
        "Farrukhabad",
        "Fatehabad",
        "Fatehgarh Sahib",
        "Fazilka",
        "Firozabad",
        "Firozpur",
        "Fuller",
        "Fungo-Kwing",
        "Gadag",
        "Gajapati",
        "Ganderbal",
        "Gandhinagar",
        "Ganjam",
        "Garhwa",
        "Gariaband",
        "Gautam Buddha Nagar",
        "Gaya",
        "Ghazipur",
        "Gir Somnath",
        "Giridih",
        "Goalpara",
        "Godda",
        "Golaghat",
        "Gomati",
        "Gonda",
        "Gondia",
        "Gopalganj",
        "Gorakhpur",
        "Gulbarga",
        "Gumla",
        "Guna",
        "Guntur",
        "Gurdaspur",
        "Gurgaon",
        "Gwalior",
        "Haflong",
        "Hailakandi",
        "Hajo",
        "Hamirpur",
        "Hanumangarh",
        "Harda",
        "Hardoi",
        "Haridwar",
        "Hassan",
        "Hathras",
        "Haveri",
        "Hazaribagh",
        "Hingoli",
        "Hisar",
        "Hooghly",
        "Hoshangabad",
        "Howrah",
        "Idukki",
        "Imphal East",
        "Imphal West",
        "Indore",
        "Iritty",
        "Itanagar",
        "Itarsi",
        "Izara",
        "Jabalpur",
        "Jagatsinghapur",
        "Jaintia Hills",
        "Jaisalmer",
        "Jajapur",
        "Jalandhar",
        "Jalaun",
        "Jalgaon",
        "Jalna",
        "Jalore",
        "Jalpaiguri",
        "Jammu",
        "Jamnagar",
        "Jamtara",
        "Jamui",
        "Janjgir-Champa",
        "Jashpur",
        "Jaunpur",
        "Jehanabad",
        "Jhabua",
        "Jhajjar",
        "Jhalawar",
        "Jhansi",
        "Jharsuguda",
        "Jhunjhunu",
        "Jind",
        "Jodhpur",
        "Kabirdham",
        "Kadapa",
        "Kaimur",
        "Kaithal",
        "Kalaburagi",
        "Kalahandi",
        "Kamareddy",
        "Kamjong",
        "Kamle",
        "Kamrup",
        "Kamrup Metropolitan",
        "Kanchipuram",
        "Kandhamal",
        "Kangra",
        "Kanker",
        "Kannauj",
        "Kannur",
        "Kanyakumari",
        "Kapurthala",
        "Karauli",
        "Karbi Anglong",
        "Kargil",
        "Karimganj",
        "Karimnagar",
        "Karnal",
        "Karur",
        "Kasaragod",
        "Kathua",
        "Katihar",
        "Katni",
        "Kaushambi",
        "Kawardha",
        "Kendrapara",
        "Kendujhar",
        "Khagaria",
        "Khammam",
        "Khandwa",
        "Khargone",
        "Kheda",
        "Kheri",
        "Khordha",
        "Khowai",
        "Khunti",
        "Kinnaur",
        "Kiphire",
        "Kishanganj",
        "Kishtwar",
        "Kodagu",
        "Koderma",
        "Kohima",
        "Kokrajhar",
        "Kolar",
        "Kolasib",
        "Kolhapur",
        "Kolkata",
        "Kollam",
        "Kondagaon",
        "Koppal",
        "Koraput",
        "Korba",
        "Koriya",
        "Kota",
        "Kothagudem",
        "Kottayam",
        "Kozhikode",
        "Krishna",
        "Kulgam",
        "Kullu",
        "Kupwara",
        "Kurukshetra",
        "Kurung Kumey",
        "Kushinagar",
        "Kutch",
        "Kuvempu Nagar",
        "Lahaul and Spiti",
        "Lakhimpur",
        "Lakhisarai",
        "Lakshadweep",
        "Latehar",
        "Latur",
        "Lawngtlai",
        "Leh",
        "Lohardaga",
        "Longleng",
        "Lower Dibang Valley",
        "Lower Siang",
        "Lower Subansiri",
        "Madhubani",
        "Madurai",
        "Mahabubabad",
        "Mahabubnagar",
        "Maharajganj",
        "Mahasamund",
        "Mahe",
        "Mahendragarh",
        "Mahisagar",
        "Maihar",
        "Maibang",
        "Mainpuri",
        "Majuli",
        "Majuli",
        "Makhdumpur",
        "Makrana",
        "Malappuram",
        "Malavalli",
        "Malda",
        "Malegaon",
        "Malkangiri",
        "Malkapur",
        "Mallappally",
        "Mallapuram",
        "Malout",
        "Malur",
        "Mamit",
        "Mananthavady",
        "Mancherial",
        "Mandi",
        "Mandla",
        "Mandsaur",
        "Mandya",
        "Manendragarh",
        "Mangalagiri",
        "Mangaldoi",
        "Mangalore",
        "Mangan",
        "Mangrol",
        "Manikpur",
        "Manimajra",
        "Manmad",
        "Mannargudi",
        "Mansa",
        "Manuguru",
        "Manvi",
        "Maqdum Bihari",
        "Margao",
        "Mariahu",
        "Marigaon",
        "Markapur",
        "Marma",
        "Marthandam",
        "Martur",
        "Masaurhi",
        "Mashal",
        "Mathabhanga",
        "Mathura",
        "Mattanur",
        "Maunath Bhanjan",
        "Mayiladuthurai",
        "Medak",
        "Medinipur",
        "Meerut",
        "Meham",
        "Mehkar",
        "Mehnagar",
        "Mehsana",
        "Melmaruvathur",
        "Memari",
        "Merta",
        "Mettupalayam",
        "Mettur",
        "Mhow",
        "Midnapore",
        "Mihijam",
        "Milak",
        "Minicoy",
        "Miraj",
        "Mirganj",
        "Mirik",
        "Miryalaguda",
        "Mirzapur",
        "Mittapally",
        "Mizoram",
        "Modasa",
        "Modinagar",
        "Moga",
        "Mohali",
        "Mokameh",
        "Mokokchung",
        "Molarband",
        "Moradabad",
        "Morbi",
        "Morena",
        "Morigaon",
        "Morshi",
        "Mothihari",
        "Motihari",
        "Mount Abu",
        "Mudalgi",
        "Muddebihal",
        "Mudhol",
        "Mukerian",
        "Mukhed",
        "Muktsar",
        "Mul",
        "Mulbagal",
        "Mullanpur",
        "Mumbai",
        "Munger",
        "Murbad",
        "Muri",
        "Murliganj",
        "Murshidabad",
        "Musafirkhana",
        "Musiri",
        "Muzaffarnagar",
        "Nabarangpur",
        "Nadia",
        "Nagaon",
        "Nagapattinam",
        "Nagaur",
        "Nagpur",
        "Nainital",
        "Nalanda",
        "Namakkal",
        "Nanded",
        "Nandurbar",
        "Narayanpur",
        "Narmada",
        "Narsinghpur",
        "Nashik",
        "Navsari",
        "Nawada",
        "Nayagarh",
        "Neemuch",
        "Nellore",
        "New Delhi",
        "Nicobar",
        "Osmanabad",
        "Other State",
        "Ourar",
        "Ongole",
        "Orchha",
        "Orissa",
        "Ottapalam",
        "Otteri",
        "Ozar",
        "Pakke Kessang",
        "Pakur",
        "Palakkad",
        "Palamu",
        "Palghar",
        "Pali",
        "Palwal",
        "Panchkula",
        "Panchmahal",
        "Panipat",
        "Panna",
        "Papum Pare",
        "Parbhani",
        "Pashchim Champaran",
        "Pasighat",
        "Patan",
        "Pathanamthitta",
        "Pathankot",
        "Patiala",
        "Patna",
        "Pauri Garhwal",
        "Perambalur",
        "Phek",
        "Pilibhit",
        "Pithoragarh",
        "Poonch",
        "Porbandar",
        "Prakasam",
        "Pratapgarh",
        "Puducherry",
        "Pulwama",
        "Pune",
        "Purba Bardhaman",
        "Purba Champaran",
        "Purbi Singhbhum",
        "Puri",
        "Purnia",
        "Purulia",
        "Quetta Valley (Kinnaur)",
        "Quilandy (Kozhikode)",
        "Qadian (Gurdaspur)",
        "Qaimoh (Kulgam)",
        "Qazigund (Anantnag)",
        "Qila Rai Pithora (South Delhi)",
        "Qila Sarai (Etah)",
        "Qilla Abdullah (Poonch)",
        "Qinqlat (North Andaman)",
        "Quemoy (Nicobar)",
        "Raichur",
        "Raigad",
        "Raigarh",
        "Raipur",
        "Raisen",
        "Rajgarh",
        "Rajkot",
        "Rajnandgaon",
        "Ramanagara",
        "Ramanathapuram",
        "Rampur",
        "Ranchi",
        "Rangareddy",
        "Ratlam",
        "Ratnagiri",
        "Rayagada",
        "Rewa",
        "Rewari",
        "Rohtak",
        "Rohtas",
        "Rudraprayag",
        "Rupnagar",
        "Rajouri",
        "Reasi",
        "Sabarkantha",
        "Sagar",
        "Saharanpur",
        "Saharsa",
        "Saiha",
        "Salem",
        "Samastipur",
        "Samba",
        "Sambalpur",
        "Sangli",
        "Sangrur",
        "Sant Kabir Nagar",
        "Sant Ravidas Nagar (Bhadohi)",
        "Saran",
        "Satara",
        "Satna",
        "Sawai Madhopur",
        "Sehore",
        "Senapati",
        "Seoni",
        "Sepahijala",
        "Serchhip",
        "Shahdara",
        "Shahdol",
        "Shahjahanpur",
        "Shajapur",
        "Shamli",
        "Sheikhpura",
        "Sheohar",
        "Sheopur",
        "Shimla",
        "Shimoga",
        "Shivpuri",
        "Shopian",
        "Shrawasti",
        "Siddharthnagar",
        "Sidhi",
        "Sikar",
        "Simdega",
        "Sindhudurg",
        "Singrauli",
        "Sirmaur",
        "Sirohi",
        "Sirsa",
        "Sitamarhi",
        "Sitapur",
        "Sivaganga",
        "Siwan",
        "Solan",
        "Solapur",
        "Sonbhadra",
        "Sonipat",
        "Sonitpur",
        "South Andaman",
        "South Delhi",
        "South Garo Hills",
        "South Goa",
        "South Salmara-Mankachar",
        "South Tripura",
        "South West Delhi",
        "South West Garo Hills",
        "South West Khasi Hills",
        "Sri Ganganagar",
        "Srikakulam",
        "Srinagar",
        "Subarnapur (Sonepur)",
        "Sukma",
        "Sultanpur",
        "Sundergarh",
        "Supaul",
        "Surat",
        "Surendranagar",
        "Surguja",
        "Suryapet",
        "Sutanuti",
        "Sutter",
        "Swai Madhopur",
        "Sylhet",
        "Sylvan Grove",
        "Séonee",
        "Tapi",
        "Tarn Taran",
        "Tawang",
        "Tehri Garhwal",
        "Thane",
        "Thanjavur",
        "The Dangs",
        "Theni",
        "Thiruvallur",
        "Thiruvarur",
        "Thoothukudi",
        "Thoubal",
        "Thrissur",
        "Tikamgarh",
        "Tinsukia",
        "Tirap",
        "Tiruchirappalli",
        "Tirunelveli",
        "Tirupathur",
        "Tiruppur",
        "Tiruvannamalai",
        "Tonk",
        "Tuensang",
        "Udalguri",
        "Udham Singh Nagar",
        "Udhampur",
        "Udupi",
        "Ujjain",
        "Ukhrul",
        "Umaria",
        "Una",
        "Unakoti",
        "Unnao",
        "Upper Siang",
        "Upper Subansiri",
        "Uttar Bastar Kanker",
        "Uttara Kannada",
        "Uttarkashi",
        "Vadodara",
        "Vaishali",
        "Valsad",
        "Varanasi",
        "Vellore",
        "Vidisha",
        "Viluppuram",
        "Virudhunagar",
        "Visakhapatnam",
        "Vizianagaram",
        "Washim",
        "Wayanad",
        "West Champaran",
        "West Garo Hills",
        "West Godavari",
        "West Jaintia Hills",
        "West Kameng",
        "West Karbi Anglong",
        "West Khasi Hills",
        "West Siang",
        "West Singhbhum",
        "West Tripura",
        "Yadgir",
        "Yamunanagar",
        "Yanam",
        "Yavatmal",
        "Yelandur",
        "Yelbarga",
        "Yellandu",
        "Yellapur",
        "Yercaud",
        "Yethapur",
        "Yol",
        "Ysr",
        "Yumnamkhunou",
        "Yusmarg",
        "Zunheboto",
        "Zirakpur",
        "Ziro",
        "Zawlnuam",
        "Zamania",
        "Zahirabad",
        "Zafarabad",
        "Zaheerabad",
        "Zahirpur",
        "Zamania",
        "Zunheboto",
        "Zira",
        "Zari",
        "Zawar Mines",
        "Zaidpur",
        "Zalod",
        "Zira",
        "Zilla Parishad",
        "Zawlnuam",
        "Zunheboto",
        "Ziro",
        "Zakir Nagar",
        "Zakhira",
        "Zikarpur",
        "Zaheerabad",
        "Zaffarwal"
    )

    var searchText by remember { mutableStateOf("") }

    val filteredCities = cities.filter { it.startsWith(searchText, ignoreCase = true) }

    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(Color.White)
    ) {
        Column() {
            Row() {
                IconButton(onClick = { /*TODO*/ }, modifier = Modifier.weight(1f)) {
                    Icon(imageVector = Icons.Filled.ArrowBack, contentDescription = "back")
                }
                TextField(
                    value = searchText,
                    onValueChange = {
                        searchText = it
                    }, label = { Text(text = "Search for city ") }, modifier = Modifier
                        .weight(5f)
                        .background(Color.White)
                )
                IconButton(onClick = { /*TODO*/ }, modifier = Modifier.weight(1f)) {
                    Icon(imageVector = Icons.Filled.Close, contentDescription = "clear")
                }
            }
            LazyColumn(
                modifier = Modifier.fillMaxSize()
            ) {
                items(filteredCities) { city ->
                    SearchItems(city)
                }
            }
        }
    }
}





